import ast
import json
import os
import re
import subprocess
import sys
import zipfile
from pathlib import Path

from .config import settings


STARTER_FILES = {
    "backend/__init__.py": "",
    "backend/main.py": '''import os
import re
from contextlib import contextmanager
from pathlib import Path

import psycopg2
from psycopg2 import sql
from psycopg2.extras import RealDictCursor
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

app = FastAPI(title="Generated by Atoms Demo")
ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
DATABASE_URL = os.environ["PROJECT_DATABASE_URL"]
TENANT_SCHEMA = os.environ["PROJECT_TENANT_SCHEMA"]
if not re.fullmatch(r"tenant_[a-f0-9]{32}", TENANT_SCHEMA):
    raise RuntimeError("Invalid project tenant schema")


@contextmanager
def database():
    connection = psycopg2.connect(DATABASE_URL)
    cursor = connection.cursor(cursor_factory=RealDictCursor)
    try:
        cursor.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(TENANT_SCHEMA)))
        cursor.execute(sql.SQL("SET search_path TO {}, public").format(sql.Identifier(TENANT_SCHEMA)))
        yield cursor
        connection.commit()
    finally:
        cursor.close()
        connection.close()


def initialize_database():
    with database() as cursor:
        cursor.execute("""CREATE TABLE IF NOT EXISTS tasks (
            id BIGSERIAL PRIMARY KEY,
            title TEXT NOT NULL,
            priority TEXT NOT NULL DEFAULT 'medium',
            done BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )""")
        cursor.execute("SELECT COUNT(*) AS count FROM tasks")
        count = cursor.fetchone()["count"]
        if count == 0:
            cursor.executemany(
                "INSERT INTO tasks(title, priority, done) VALUES (%s, %s, %s)",
                [("Review product brief", "high", True), ("Interview three customers", "high", False), ("Ship onboarding update", "medium", False)],
            )


initialize_database()


class TaskCreate(BaseModel):
    title: str
    priority: str = "medium"


class TaskUpdate(BaseModel):
    title: str | None = None
    priority: str | None = None
    done: bool | None = None


def task_or_404(cursor, task_id: int):
    cursor.execute("SELECT * FROM tasks WHERE id = %s", (task_id,))
    task = cursor.fetchone()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    return dict(task)


@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.get("/api/tasks")
def list_tasks():
    with database() as connection:
        connection.execute("SELECT * FROM tasks ORDER BY id DESC")
        return [dict(row) for row in connection.fetchall()]


@app.post("/api/tasks", status_code=201)
def create_task(body: TaskCreate):
    title = body.title.strip()
    if not title:
        raise HTTPException(status_code=422, detail="Title is required")
    with database() as connection:
        connection.execute("INSERT INTO tasks(title, priority) VALUES (%s, %s) RETURNING id", (title, body.priority))
        task_id = connection.fetchone()["id"]
        return task_or_404(connection, task_id)


@app.patch("/api/tasks/{task_id}")
def update_task(task_id: int, body: TaskUpdate):
    with database() as connection:
        current = task_or_404(connection, task_id)
        connection.execute(
            "UPDATE tasks SET title = %s, priority = %s, done = %s WHERE id = %s",
            (body.title if body.title is not None else current["title"], body.priority if body.priority is not None else current["priority"], body.done if body.done is not None else current["done"], task_id),
        )
        return task_or_404(connection, task_id)


@app.delete("/api/tasks/{task_id}", status_code=204)
def delete_task(task_id: int):
    with database() as connection:
        task_or_404(connection, task_id)
        connection.execute("DELETE FROM tasks WHERE id = %s", (task_id,))


@app.get("/api/summary")
def summary():
    with database() as connection:
        connection.execute("SELECT COUNT(*) AS count FROM tasks")
        total = connection.fetchone()["count"]
        connection.execute("SELECT COUNT(*) AS count FROM tasks WHERE done = TRUE")
        completed = connection.fetchone()["count"]
    return {"total": total, "completed": completed, "open": total - completed}


app.mount("/assets", StaticFiles(directory=FRONTEND), name="assets")


@app.get("/{path:path}")
def frontend(path: str = ""):
    candidate = FRONTEND / path
    if path and candidate.is_file():
        return FileResponse(candidate)
    return FileResponse(FRONTEND / "index.html")
''',
    "frontend/index.html": '''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Flowlist — Work that moves</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <div class="app-shell">
      <header><a class="brand"><span>✦</span> flowlist</a><span class="saved">● Saved to database</span></header>
      <main>
        <section class="hero"><p>PERSONAL WORKSPACE</p><h1>Work that moves<br/><em>with you.</em></h1><span>A small, persistent task system powered by a real backend.</span></section>
        <section class="metrics"><article><small>ALL TASKS</small><strong id="total">0</strong></article><article><small>OPEN</small><strong id="open">0</strong></article><article><small>COMPLETED</small><strong id="completed">0</strong></article></section>
        <section class="workspace">
          <form id="task-form"><input id="task-title" required placeholder="What needs to happen?"/><select id="priority"><option value="medium">Medium</option><option value="high">High</option><option value="low">Low</option></select><button>Add task</button></form>
          <div class="toolbar"><h2>Today</h2><div><button class="filter active" data-filter="all">All</button><button class="filter" data-filter="open">Open</button><button class="filter" data-filter="done">Done</button></div></div>
          <div id="task-list" class="task-list"></div>
          <p id="empty" class="empty" hidden>No tasks in this view.</p>
        </section>
      </main>
    </div>
    <script src="./app.js"></script>
  </body>
</html>
''',
    "frontend/styles.css": ''':root{font-family:Inter,ui-sans-serif,system-ui;color:#211d29;background:#f4f1f6}*{box-sizing:border-box}body{margin:0}.app-shell{min-height:100vh}header{height:68px;background:#17131d;color:white;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,calc((100vw - 1040px)/2))}.brand{font-size:18px;font-weight:800}.brand span{color:#9c7bf0;margin-right:8px}.saved{font-size:11px;color:#9d96a6}.saved:first-letter{color:#4bd49a}main{max-width:1040px;margin:auto;padding:55px 0}.hero p{font-size:10px;letter-spacing:.18em;color:#7f7488}.hero h1{font-size:55px;line-height:1.02;letter-spacing:-.055em;margin:10px 0 16px}.hero h1 em{font-style:normal;color:#7655dd}.hero>span{color:#847c89}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:35px 0 18px}.metrics article,.workspace{background:white;border:1px solid #e2dde6;border-radius:15px;padding:20px;box-shadow:0 9px 30px #2a183b0c}.metrics small{color:#9a919f;font-size:9px;letter-spacing:.12em}.metrics strong{display:block;font-size:29px;margin-top:8px}.workspace{padding:22px}form{display:grid;grid-template-columns:1fr 125px auto;gap:8px}input,select{border:1px solid #ddd7e1;border-radius:9px;padding:12px;background:#fbfafc;outline:none}input:focus{border-color:#8266df;box-shadow:0 0 0 3px #8061df17}button{border:0;border-radius:9px;padding:11px 15px;background:#241f2b;color:white;font-weight:600}.toolbar{display:flex;align-items:center;justify-content:space-between;margin:28px 0 8px}.toolbar h2{font-size:18px}.toolbar button{background:transparent;color:#8d8491;padding:7px 10px;font-size:11px}.toolbar button.active{background:#eee9f5;color:#6d4acb}.task{display:grid;grid-template-columns:auto 1fr auto auto;align-items:center;gap:12px;border-top:1px solid #eeeaf0;padding:14px 4px}.check{width:23px;height:23px;padding:0;border:1px solid #d3ccd8;background:white;color:white;border-radius:7px}.task.done .check{background:#7252d2;border-color:#7252d2}.task.done .title{text-decoration:line-through;color:#a39ba7}.title{font-size:13px}.priority{font-size:9px;text-transform:uppercase;letter-spacing:.08em;padding:5px 7px;border-radius:12px;background:#f2edf8;color:#7555c7}.priority.high{background:#fff0f1;color:#c24e62}.delete{background:transparent;color:#b0a7b3;padding:5px 8px}.empty{text-align:center;color:#99909e;padding:30px}.error{color:#c23c52;font-size:12px}@media(max-width:760px){header{padding:0 18px}main{padding:30px 18px}.hero h1{font-size:40px}.metrics{grid-template-columns:1fr 1fr}.metrics article:last-child{grid-column:1/-1}form{grid-template-columns:1fr}.task{grid-template-columns:auto 1fr auto}.task .priority{display:none}}''',
    "frontend/app.js": '''let tasks=[];
let filter="all";
const request=async(path,options={})=>{const response=await fetch(`./api${path}`,{headers:{"Content-Type":"application/json"},...options});if(!response.ok)throw new Error((await response.json()).detail||"Request failed");return response.status===204?null:response.json()};
const escapeHtml=value=>value.replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
async function refresh(){tasks=await request("/tasks");const summary=await request("/summary");for(const key of ["total","open","completed"])document.querySelector(`#${key}`).textContent=summary[key];render()}
function render(){const visible=tasks.filter(task=>filter==="all"||(filter==="done"?task.done:!task.done));document.querySelector("#empty").hidden=visible.length>0;document.querySelector("#task-list").innerHTML=visible.map(task=>`<article class="task ${task.done?"done":""}" data-id="${task.id}"><button class="check" aria-label="Toggle ${escapeHtml(task.title)}">✓</button><span class="title">${escapeHtml(task.title)}</span><span class="priority ${task.priority}">${task.priority}</span><button class="delete" aria-label="Delete ${escapeHtml(task.title)}">×</button></article>`).join("")}
document.querySelector("#task-form").addEventListener("submit",async event=>{event.preventDefault();const input=document.querySelector("#task-title");await request("/tasks",{method:"POST",body:JSON.stringify({title:input.value,priority:document.querySelector("#priority").value})});input.value="";await refresh()});
document.querySelector("#task-list").addEventListener("click",async event=>{const taskElement=event.target.closest(".task");if(!taskElement)return;const task=tasks.find(item=>item.id===Number(taskElement.dataset.id));if(event.target.closest(".check"))await request(`/tasks/${task.id}`,{method:"PATCH",body:JSON.stringify({done:!task.done})});if(event.target.closest(".delete"))await request(`/tasks/${task.id}`,{method:"DELETE"});await refresh()});
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{document.querySelector(".filter.active").classList.remove("active");button.classList.add("active");filter=button.dataset.filter;render()}));
refresh().catch(error=>{document.querySelector("#task-list").innerHTML=`<p class="error">${escapeHtml(error.message)}</p>`});
''',
    "README.md": "# Generated application\n\nA complete FastAPI + HTML/CSS/JavaScript website generated by Atoms Demo.\n",
}


def project_root(project_id: str) -> Path:
    return settings.workspace_root / project_id


def ensure_workspace(project_id: str) -> Path:
    root = project_root(project_id)
    root.mkdir(parents=True, exist_ok=True)
    for relative, content in STARTER_FILES.items():
        target = root / relative
        if not target.exists():
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
    return root


def safe_path(root: Path, relative: str) -> Path:
    if not relative or relative.startswith(("/", "\\")):
        raise ValueError("必须使用项目内相对路径")
    resolved = (root / relative).resolve()
    if root.resolve() not in resolved.parents and resolved != root.resolve():
        raise ValueError("路径越界")
    return resolved


def list_files(root: Path) -> list[str]:
    ignored = {"__pycache__", ".git", ".atoms"}
    return sorted(
        str(path.relative_to(root)).replace("\\", "/")
        for path in root.rglob("*")
        if path.is_file() and not any(part in ignored for part in path.parts)
    )


def run_checks(root: Path) -> dict:
    required = ["backend/main.py", "frontend/index.html"]
    missing = [name for name in required if not (root / name).is_file()]
    errors: list[str] = []
    backend_source = ""
    for path in (root / "backend").rglob("*.py"):
        try:
            source = path.read_text(encoding="utf-8")
            backend_source += "\n" + source
            ast.parse(source, filename=str(path))
        except (SyntaxError, UnicodeDecodeError) as exc:
            errors.append(str(exc))
    lower_backend = backend_source.lower()
    if "sqlite" in lower_backend:
        errors.append("生成项目不得使用 SQLite；必须使用平台注入的 PostgreSQL 租户 schema")
    if "project_tenant_schema" not in lower_backend or "psycopg2" not in lower_backend:
        errors.append("后端必须保留 PROJECT_TENANT_SCHEMA 与 psycopg2 PostgreSQL 租户连接")
    if not re.search(r"@app\.(post|patch|put|delete)\(\s*['\"]\/api\/", lower_backend):
        errors.append("后端至少需要一个真实的 POST/PATCH/PUT/DELETE API")
    if not errors and not missing:
        try:
            check_env = os.environ.copy()
            check_env["PROJECT_DATABASE_URL"] = settings.database_url.replace("postgresql+psycopg2://", "postgresql://")
            check_env["PROJECT_TENANT_SCHEMA"] = f"tenant_{root.name.replace('-', '')}"
            imported = subprocess.run(
                [
                    sys.executable,
                    "-c",
                    "from fastapi.testclient import TestClient; from backend.main import app; "
                    "routes=[(r.path,r.methods) for r in app.routes if r.path.startswith('/api/')]; "
                    "assert any('GET' in m for _,m in routes); "
                    "assert any(m & {'POST','PATCH','PUT','DELETE'} for _,m in routes); "
                    "assert TestClient(app).get('/api/health').status_code == 200",
                ],
                cwd=root,
                capture_output=True,
                text=True,
                timeout=15,
                env=check_env,
            )
            if imported.returncode != 0:
                errors.append((imported.stderr or imported.stdout)[-3000:])
        except (subprocess.SubprocessError, OSError) as exc:
            errors.append(f"backend import check failed: {exc}")
    try:
        html = (root / "frontend/index.html").read_text(encoding="utf-8")
        javascript = "\n".join(path.read_text(encoding="utf-8") for path in (root / "frontend").rglob("*") if path.is_file() and path.suffix.lower() in {".js", ".jsx", ".ts", ".tsx"})
        if "<html" not in html.lower() or "</html>" not in html.lower():
            errors.append("frontend/index.html 缺少完整 HTML 文档结构")
        if "fetch(" not in javascript and "fetch(`" not in javascript:
            errors.append("前端必须通过 API 获取真实数据")
        if not any(method in javascript.upper() for method in ['METHOD:"POST"', 'METHOD: "POST"', 'METHOD:"PATCH"', 'METHOD: "PATCH"', 'METHOD:"DELETE"', 'METHOD: "DELETE"', 'METHOD:"PUT"', 'METHOD: "PUT"']):
            errors.append("前端必须调用至少一个写接口，使页面可真实操作")
        if not javascript.strip():
            errors.append("前端至少需要一个 JavaScript/TypeScript 源文件")
    except OSError as exc:
        errors.append(str(exc))
    return {"ok": not missing and not errors, "missing": missing, "errors": errors, "files": list_files(root)}


def save_snapshot(root: Path, version_dir: Path, version_number: int) -> Path:
    version_dir.mkdir(parents=True, exist_ok=True)
    archive = version_dir / f"version-{version_number}.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as bundle:
        for path in root.rglob("*"):
            if path.is_file() and ".atoms" not in path.parts:
                bundle.write(path, path.relative_to(root))
    return archive


def project_manifest(root: Path) -> str:
    result = {"files": []}
    for relative in list_files(root):
        path = root / relative
        result["files"].append({"path": relative, "bytes": path.stat().st_size})
    return json.dumps(result, ensure_ascii=False)
